### PR TITLE
Corvin_Ansorge_Solution_Exercise_09_MCC:0.5319687835541821

### PR DESCRIPTION
**Pull request by CorvinAn97**

### CODE REVIEW

**Comment by CorvinAn97** [comment]
You are right, sorry. This PR is not (yet) ready. Will add this to the description.

**Review by fabischw — CHANGES_REQUESTED** [review]
Looks good in general but please consider adjusting your imports as they're using paths dependant on the cwd (current working directory). Examples of how this can be achived in jupyter notebook can be found in my or in @LeMixer 's notebooks for week 8 or 9.

You should also consider adding some more comments, however I'd see this as optional here as the code is pretty self-explanatory. Reason for CR is the import.

**Review by fabischw — APPROVED** [review]
Problems were adressed.

**Comment by fabischw** [comment]
I will be merging this PR if it does not get merged by the PR creator within the next 3 days in an effort to clean up the repo (More information can be found in [Issue #228](https://github.com/dhbw-ma-ppp/ppp-2023/issues/228))

**Pull request merged**
