### PR TITLE
Jonas week08

### PR DESCRIPTION
**Pull request by DrKeks1010**
Analysis conclusion:
People with one of these attributes have a higher chance of surviving:
Females, 1st class passengers, young children, no relatives onboard.

In total, the only relevant columns for the analysis are:
Sex, Pclass, Age and Fam

Complete analysis
[Titanic Analysis.pdf](https://github.com/dhbw-ma-ppp/ppp-2023/files/13510768/Titanic.Analysis.pdf)

### CODE REVIEW

**Review by RubelOS — APPROVED** [review]
This is an extremely clean looking document. You did an absolutely great job!

**Comment by RubelOS** [comment]
What technique did u use for creating this pdf file? LaTeX? or WYSIWYG?

**Comment by DrKeks1010** [comment]
> What technique did u use for creating this pdf file? LaTeX? or WYSIWYG?

I used Word, so WYSIWYG.

**Comment by fabischw** [comment]
I will be merging this PR if it does not get merged by the PR creator within the next 3 days in an effort to clean up the repo (More information can be found in [Issue #228](https://github.com/dhbw-ma-ppp/ppp-2023/issues/228))

**Pull request merged**
