### PR TITLE
Lösung der ersten Aufgaben

### PR DESCRIPTION
**Pull request by TomKnoden**

### CODE REVIEW

**Review by The-Linux-User — CHANGES_REQUESTED** [review]
Int Division required here, so use // instead of / in line 7

**Review by LeMixer — CHANGES_REQUESTED** [review]

**Comment by atrejut** [comment]
@TomKnoden please create separate PRs for each week (with correct labels) in the future...

**Review by LeMixer — CHANGES_REQUESTED** [review]
You've added the solution for the third week in the same pull request again. Please open a separate pull request and upload your solution in another branch.

**Review by The-Linux-User — APPROVED** [review]

**Comment by atrejut** [comment]
@TomKnoden  please try to get this old PR merged -- take a look at the reviews, things should be easy enough to fix now.

**Pull request closed without merging**
