### PR TITLE
Reupload zu Woche 04 (16694270)

### PR DESCRIPTION
**Pull request by TomKnoden**
As stated in the title, this PR simply is a reupload of my solution for week 01. There have been problems concerning the former branch in which the file was located in. These problems have been fixed.
Also there have been some improvements made to the code that should enhance it's functionality and efficiency.

### CODE REVIEW

**Review by RubelOS — DISMISSED** [review]
Everything good to go

**Comment by RubelOS** [comment]
Please merge all of your PRs. Thank you for fixing

**Review by fabischw — CHANGES_REQUESTED** [review]
Please add the original problem description or a comment that refers to the original problem description. Please also add the original commands array(
```py
program = [1,2,3,4,5,6,7]#numbers are merely an example, you should either copy the original array here or asign the commands array to the program code
```
This makes testing and reviewing your code easier as the reviewer has to type all commands in the terminal if you want to test the codes functionality.
Should be a small fix, you might even be able to just edit the file on github itself.

**Review by fabischw — APPROVED** [review]
requested changes were implemented.

**Pull request merged**
