### PR TITLE
exercise_01 completed

### PR DESCRIPTION
**Pull request by LeMixer**

### CODE REVIEW

**Review by fabischw — APPROVED** [review]
LGTM!

**Review by atrejut — COMMENTED** [review]
looks like you have an empty file under `Exercies/RobertWalz` and the actual solution directly in `Exercises`?

**Review by atrejut — CHANGES_REQUESTED** [review]
you've moved the template to a new location with this change. please leave it in place and add a new file for your solution...

**Review by fabischw — CHANGES_REQUESTED** [review]
You created a new file called "excercises_01.py". The original file was called "exercises_01.py". (Small typo but merging this PR would create a second file instead of just leaving the source file unchanged)

**Review by fabischw — APPROVED** [review]
Requested changes were implemented. Please pick a more descriptive commit message next time.

**Review by atrejut — APPROVED** [review]

**Pull request merged**
